application: codereview
version: 1
runtime: python
api_version: 1

handlers:

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static/(.*)
  static_files: static/\1
  upload: static/\w+\.\w+

- url: .*
  script: main.py
